### ISSUE TITLE
ERROR in ./node_modules/react-slot-machine-gen/src/react-slot-machine.js

### ISSUE THREAD

**Issue by NovaTheMachine** [nuxy/react-slot-machine-gen#5]
Hello ! 

i have this error with react 

`ERROR in ./node_modules/react-slot-machine-gen/src/react-slot-machine.js

Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: C:\Users\33624\Desktop\OZALENTOURS2.0\Machine\machine\node_modules\react-slot-machine-gen\src\react-slot-machine.js: Support for the experimental syntax 'jsx' isn't currently enabled (38:7):

  36 |   render() {
  37 |     return (
> 38 |       <div id={this.props.id} className="slot-machine" ref="wrapper"></div>
     |       ^
  39 |     );
  40 |   }
  41 | };`

**Comment by nuxy** [comment]
Looks like a dependency is not installed.  Please confirm the following:

```
$ cd ./react-slot-machine-gen
$ npm install
$ npm run build
$ npm run webpack
```

Which should result with the output below.
```

> react-slot-machine-gen@1.1.1 webpack
> node_modules/.bin/webpack-cli demo/index.js --config demo/webpack.config.js --output-path demo/assets

Hash: 6669e11d35a1f51f0e76
Version: webpack 4.43.0
Time: 1138ms
Built at: 05/04/2022 9:32:37 PM
     Asset      Size  Chunks             Chunk Names
bundle.css  1.52 KiB    main  [emitted]  main
 bundle.js     1 MiB    main  [emitted]  main
Entrypoint main = bundle.css bundle.js
[./demo/index.js] 4.73 KiB {main} [built]
[./dist/react-slot-machine.js] 3.92 KiB {main} [built]
    + 19 hidden modules
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/slot-machine-gen/dist/slot-machine.min.css:
    Entrypoint mini-css-extract-plugin = *
       2 modules
```

If this still doesn't work the issue may be environment specific.

**Comment by nuxy** [comment]
At second glance of the error you provided above. It seems you are building the library from within your own project.

That said, make sure your project `.babelrc` has defined the following presets and you should be good to go.
```
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react"
  ]
}
```

Closing this issue.

**Comment by darshanhande11** [comment]
@nuxy This error is still prevalent when installing `react-slot-machine-gen` from npm and trying to use it in a react project. I have tried both of the fixes you suggested above but the error doesn't go away. Any other fix, you might suggest?
