### ISSUE TITLE
i cannot implement webpack error ref 

### ISSUE THREAD

**Issue by JoseMariani** [nuxy/react-slot-machine-gen#8]
Who can implement this in react 18 project generate with nextjs? 

This is the project repo:  https://github.com/cornflourblue/next-js-13-mysql-registration-login-example  

MY steps: 
1-Make me error i install npm install react-slot-machine-gen 
2-Copy use section in this repo, in my page in pages directory... 

and get this error: 
```
Failed to compile
./node_modules/react-slot-machine-gen/src/react-slot-machine.js
Module parse failed: Unexpected token (38:6)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   render() {
|     return (
>       <div id={this.props.id} className="slot-machine" ref="wrapper"></div>
|     );
|   }
```

Please some body can help me??

**Comment by nuxy** [comment]
> Who can implement this in react 18 project generate with nextjs?

This is a configuration issue in your project `webpack.config.js`

A working example can be found [here](https://github.com/nuxy/react-slot-machine-gen/blob/master/demo/webpack.config.js).

**Comment by nuxy** [comment]
If you're still having issues you can always integrate the [main library](https://github.com/nuxy/slot-machine-gen) into your Next.js project.

Closing this issue.

**Comment by JoseMariani** [comment]
Yes, but I think the problem comes for two reasons, the first one doesn't work with versions of react greater than 16?

And even if I implement the original library and turn it into my own component (which I already did) how do I make it work if I don't implement webpack?

**Comment by nuxy** [comment]
> Yes, but I think the problem comes for two reasons, the first one doesn't work with versions of react greater than 16?

This library should work with the latest release `react ^18.2.0`.  I have confirmed this locally using the demo.

> And even if I implement the original library and turn it into my own component (which I already did) how do I make it work if I don't implement webpack?

The initial error you received was a `webpack` so I assume it is [configured in your Next.js application](https://nextjs.org/docs/pages/api-reference/next-config-js/webpack).

That said, in the case of this package `webpack` is used to generate CSS/JS sources used by the demo.  However, this is **not required when using the original library**.  In that case all you need is to ensure the files are transpiled using [Babel](https://nextjs.org/docs/pages/building-your-application/configuring/babel).

**Comment by nuxy** [comment]
In case you did not review the issue queue..

According to [this post](https://github.com/nuxy/react-slot-machine-gen/issues/4) you need to use [server-side rendering](https://nextjs.org/docs/pages/building-your-application/rendering/server-side-rendering) in order for this package to work with Next.js
